environment_config:
  path: environment_config.dart # optional, result file path against `lib/` folder
  class: EnvironmentConfig # optional, class name

  fields: # set of fields for command
    serviceUrl:
      default: ""
    mock:
      type: bool
      default: false