import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// This associates 'new_request.dart' with the code generated by Freezed
part 'new_request.freezed.dart';

@freezed
class PostRequestInput with _$PostRequestInput {
  const factory PostRequestInput({
    required String title,
    required String status,
  }) =
  _PostRequestInput; // Named private constructor for the actual implementation
}

@freezed
class DeleteRequestInput with _$DeleteRequestInput {
  const factory DeleteRequestInput({
    required String requestID,
  }) = _DeleteRequestInput;
}

@freezed
class PostRequestOutput with _$PostRequestOutput {
  const factory PostRequestOutput({
    required String id,
  }) =
  _PostRequestOutput;
}

@freezed
class DeleteRequestOutput with _$DeleteRequestOutput {
  const factory DeleteRequestOutput({
    required bool success,
  }) =
  _DeleteRequestOutput;
}
