import 'package:freezed_annotation/freezed_annotation.dart';

// This associates 'vehicle_request.dart' with the code generated by Freezed
part 'vehicle_request.freezed.dart';

// Immutable data class representing a vehicle request.
@freezed
class VehicleRequest with _$VehicleRequest{
  const factory VehicleRequest({
    required String requestId,
    required String startDate,
    required String endDate,
    required String assetType,
  }) = _VehicleRequest;
}

// Immutable data class representing the vehicle list.
@freezed
class VehicleList with _$VehicleList {
  const factory VehicleList({
    required int id,
    required String type,
    required DateTime fromTime,
    required DateTime toTime,
  }) = _VehicleList;
}

@freezed
class ResourceField with _$ResourceField {
  const factory ResourceField({
    required bool success,
    required int id,
    required String result
  }) = _ResourceField;
}

