// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7Gy1ONapgxzk_wcgVra4mmQ88A8qM_E',
    appId: '1:627067556312:web:5c5476d56943323e27a2ad',
    messagingSenderId: '627067556312',
    projectId: 'fireapp-13e78',
    authDomain: 'fireapp-13e78.firebaseapp.com',
    storageBucket: 'fireapp-13e78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFfSV-Ik9L8EmI_OQJ7VwxpX-U0BhIw8',
    appId: '1:627067556312:android:0ae90b8550ee0d3e27a2ad',
    messagingSenderId: '627067556312',
    projectId: 'fireapp-13e78',
    storageBucket: 'fireapp-13e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLl-IAxnmq4G5WMqaxs_ctXKOhv6NxjKo',
    appId: '1:627067556312:ios:253a5662057fd48827a2ad',
    messagingSenderId: '627067556312',
    projectId: 'fireapp-13e78',
    storageBucket: 'fireapp-13e78.appspot.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLl-IAxnmq4G5WMqaxs_ctXKOhv6NxjKo',
    appId: '1:627067556312:ios:253a5662057fd48827a2ad',
    messagingSenderId: '627067556312',
    projectId: 'fireapp-13e78',
    storageBucket: 'fireapp-13e78.appspot.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT7Gy1ONapgxzk_wcgVra4mmQ88A8qM_E',
    appId: '1:627067556312:web:061190ba5c6e29cf27a2ad',
    messagingSenderId: '627067556312',
    projectId: 'fireapp-13e78',
    authDomain: 'fireapp-13e78.firebaseapp.com',
    storageBucket: 'fireapp-13e78.appspot.com',
  );
}
