name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: flutter pub get
      working-directory: ./fireapp
    - run: flutter pub run build_runner build
      working-directory: ./fireapp
    - run: flutter gen-l10n
      working-directory: ./fireapp
    - run: flutter build apk
      working-directory: ./fireapp
    - name: version
      run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/apk/debug/app-debug.apk
        asset_content_type: application/vnd.android.package-archive
