name: Unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: flutter pub get
      working-directory: ./fireapp
    - run: flutter pub run build_runner build
      working-directory: ./fireapp
    - run: flutter gen-l10n
      working-directory: ./fireapp
    - run: flutter test --coverage
      working-directory: ./fireapp
    - uses: actions/upload-artifact@master
      with:
        name: lcov
        path: ./fireapp/coverage/lcov.info
    - uses: actions/upload-artifact@master
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      with:
        name: build
        path: ./fireapp
  report:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - uses: actions/download-artifact@master
      with:
        name: build
        path: ./fireapp
    - run: flutter pub global activate remove_from_coverage
    - run: flutter pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r "\.g\.dart$" -r "\.freezed\.dart$" -r "\.config\.dart$" -r "di\.dart$" -r "test" -r "_navigation\.dart$"
      working-directory: ./fireapp
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ./fireapp/coverage/lcov.info
        minimum-coverage: 90
        working-directory: ./fireapp
        artifact-name: test-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true
    
      
